language: node_js

notifications:
  email: false

node_js:
  - "10"

script:
  - npm run bootstrap && npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $CI_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
